apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config-app
  files:
  - mytoken.txt
  - myopentoken.txt
  - temp_transfer_folder_id.txt
  - alishare_list.txt
  - docker_address.txt
  - guestpass.txt
  - guestlogin.txt
  - show_my_ali.txt
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
